<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
  <script type="text/javascript" src="my_player.js"></script>
  <meta charset="utf-8">
  <title>Robot interface</title>
</head>
<body onload="init_api()">
  <div class="card" style="width: 640px;">
    <div id="myVideo" class="card-img-top" style="height: 480px; background-color: black;"> </div>
      <div class="card-body" style="display: inline-flex;">
	<div>
          <button onclick="connect()" value="PLAY" class="btn btn-success">PLAY</button>
        </div>
        <table>
          <tr>
            <td></td>
            <td>
	      <button id="buttonForward" class="btn btn-primary">
	        <img src="imgs/arrow-up.svg"></i>
              </button>
            </td>
            <td></td>
          </tr>
          <tr>
            <td>
	      <button id="buttonLeft" class="btn btn-primary">
	        <img src="imgs/arrow-left.svg"></i>
              </button>
            </td>
  	    <td></td>
            <td>
	      <button id="buttonRight" class="btn btn-primary">
	        <img src="imgs/arrow-right.svg"></i>
              </button>
            </td>
          </tr>
          <tr>
           <td></td>
           <td>
	     <button id="buttonDown" class="btn btn-primary">
	       <img src="imgs/arrow-down.svg"></i>
             </button>
           </td>
           <td></td>
          </tr>
        </table>
      </div>
  </div>
  <script src="./vendor/components/jquery/jquery.min.js"></script>

</body>
</html>
